# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto bump version number

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint and test
    runs-on: ubuntu-latest

    outputs:
      commit: ${{ steps.commit.outputs.commit_hash }}
  
    steps:
      - uses: actions/checkout@v3
      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch 
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Next Release Number
        run: echo ${{ steps.versioning.outputs.version }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.versioning.outputs.version }}
          message: "Automatically bumped version to ${{ steps.versioning.outputs.version }}"

      - name: Store version
        run: echo ${{ steps.versioning.outputs.version }} > version.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_message: "Bump version patch to ${{ steps.versioning.outputs.version }}"
  echoit:
    uses: ./.github/workflows/echo-version.yml
    with:
      commit: ${{ needs.lint.outputs.commit }}
    secrets: inherit
    needs: lint